title = "Robellion"

[params.author] 
name = "Robel A. Istefanos"
image = "img/itsrobel.jpg"
# headline = "Programmer  -  Developer -  Designer"
bio = "All of my subjective opinions are objectively correct, subjectively"
links = [
  { linkedin = "https://www.linkedin.com/in/robel-schwarz-015010275/" },
  { instagram = "https://www.instagram.com/the_robellion/" },
    {github = "https://github.com/itsrobel"},
]
