title = "The Robellion"

[params.author]
name = "Robel A. Istefanos"
image = "img/itsrobel.jpg"
headline = "A generally awesome human, who occasionally writes code"
bio = "I all of my subjective opinions are objectively correct, subjectively"
# links = [
#   { twitter = "https://twitter.com/username" }
# ]
