title = "The Robellion"

[params.author]
name = "The Robellion"
image = "img/author.jpg"
headline = "A generally awesome human, who occasionally writes code"
bio = "A little bit about me"
# links = [
#   { twitter = "https://twitter.com/username" }
# ]
