title = "Robellion"

[params.author] 
name = "Robel A. Istefanos"
image = "img/itsrobel.jpg"
headline = "If I have seen further, it is by standing on the shoulders of gaints"
bio = "All of my subjective opinions are objectively correct, subjectively"
# links = [
#   { twitter = "https://twitter.com/username" }
# ]
