# [[main]]
#   name = "Blog"
#   pageRef = "posts"
#   weight = 10


[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Resume"
  # pageRef = "resume"
  url = "/resume/"
  weight = 20

[[main]]
  name = "Topics"
  pageRef = "topics"
  weight = 40

[[main]]
  name = "GitHub"
  url = "https://github.com/amarshavir"
  weight = 50
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"


[[main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/robel-schwarz-015010275/"
  weight = 50
  [main.params]
    icon = "linkedin"
    showName = false
    target = "_blank"

[[main]]
  name = "instagram"
  url = "https://www.instagram.com/the_robellion/"
  weight = 50
  [main.params]
    icon = "instagram"
    showName = false
    target = "_blank"


[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    # icon = "search"

# [[main]]
#   identifier = "appearance"
#   weight = 99
#   [main.params]
#     action = "appearance"
#     icon = "appearance"

[[footer]]
  name = "Privacy"
  pageRef = "privacy"
