colorScheme = "gruvbox-dark"

defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true
enableQuicklink = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[header]
  layout = "hybrid" # valid options: basic, hamburger, hybrid, custom
  # logo = "img/logo.jpg"
  # logoDark = "img/dark-logo.jpg"
  # showTitle = true

[homepage]
  layout = "custom" # valid options: page, profile, custom
  showRecent = true
  recentLimit = 4
# [[homepage]]
#     # layout = "p"
#     showRecent = true
#
#
[footer]
  showAppearanceSwitcher = false
    showThemeAttribution = false


[article]
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = false
  showWordCount = false
  showComments = false

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = true
  showTaxonomies = false
  groupByYear = false
  paginationWidth = 4
